"""Weak/windowed moment methods for stochastic-polynomial inference."""

from ku_weak_moment.windows import (
    gaussian_window,
    cauchy_like_window,
    tukey_compact_window,
    hann_value_window,
    WINDOW_REGISTRY,
)
from ku_weak_moment.moments import weak_moment, weak_central_moment, raw_moment
from ku_weak_moment.estimators import (
    cauchy_mle_location,
    tukey_biweight_location,
    weak_pmm_location,
    cauchy_mle_regression,
    weak_pmm_regression,
    weak_pmm2_location,
    weak_pmm2_regression,
    weak_pmm3_location,
    weak_pmm3_regression,
    weak_cf_location,
    weak_cf_regression,
    lad_regression,
    ols_regression,
    tukey_biweight_regression,
    classical_pmm2_regression,
    sample_mean_location,
    median_location,
)

__all__ = [
    "gaussian_window",
    "cauchy_like_window",
    "tukey_compact_window",
    "hann_value_window",
    "WINDOW_REGISTRY",
    "weak_moment",
    "weak_central_moment",
    "raw_moment",
    "cauchy_mle_location",
    "tukey_biweight_location",
    "weak_pmm_location",
    "cauchy_mle_regression",
    "weak_pmm_regression",
    "weak_pmm2_location",
    "weak_pmm2_regression",
    "weak_pmm3_location",
    "weak_pmm3_regression",
    "weak_cf_location",
    "weak_cf_regression",
    "lad_regression",
    "ols_regression",
    "tukey_biweight_regression",
    "classical_pmm2_regression",
    "sample_mean_location",
    "median_location",
]
